//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parte2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public int idAuto { get; set; }
        public string Placa { get; set; }
        public string Marca { get; set; }
        public string Combustible { get; set; }
        public int Precio { get; set; }
    }
}
